config/routes.rb
Rails.application.routes.draw do
  root 'talks#index'

  resources :talks do
    resources :comments
    resources :recordings
  end

  resources :emcee
  resources :speakers

  devise_for :users

end

app/models/application_helper.rb
module ApplicationHelper
  # this method will embed the code from the partial
  def youtube_video(url)
    render :partial => 'media/video', :locals => { :url => url }
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :talk
  belongs_to :user

  validates :content, presence: { message: "You cannot submit a blank comment" }
  validates :talk_id, presence: true
  validates :user_id, presence: true
end

app/models/filler_word.rb
class FillerWord < ActiveRecord::Base
  has_many :wasted_words
  has_many :talks, through: :wasted_words
end

app/models/speech_processor.rb
require "pocketsphinx-ruby"

class SpeechProcessor
  include Pocketsphinx

  attr_accessor :decoder

  def initialize
    @decoder = Decoder.new(Configuration.default)
  end

  def decode(file_path)
    @decoder.decode file_path
    @decoder.hypothesis
  end
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  has_many :comments
  has_many :wasted_words
  has_many :filler_words, through: :wasted_words
  belongs_to :user

  validates :topic, presence: true
  validates :date, presence: true

  def count_fillers
    word_counts = {}
    filler_words.each do |filler|
      key = filler.word.scan(/[a-z]/).join
      (word_counts.key?(key))? word_counts[key] += 1 : word_counts[key] = 1
    end
    word_counts
  end

  def find_wasted_words
    fillers = FillerWord.all
    fillers.each do |filler|
      regexp = Regexp.new filler.word
      count = transcript.scan(regexp).length
      count.times { WastedWord.create(filler_word_id: filler.id, talk_id: id) }
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :talks
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/wasted_word.rb
class WastedWord < ActiveRecord::Base
  belongs_to :filler_word
  belongs_to :talk
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @talk = Talk.find(params[:talk_id])
    @comment = Comment.new(talk_id: @talk.id, content: params[:comment][:content], user_id: current_user.id)
    if @comment.save
      flash[:notice] = 'Thanks for commenting'
    else
      @comment.errors.full_messages.each do |error|
        flash[:alert] = "Comment can't be blank"
      end
    end
    redirect_to talk_path(@talk)
  end

  def edit
    @comment = Comment.find(params[:id])
    @talk = @comment.talk
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.content = params[:comment][:content]
    if @comment.save
      flash[:notice] = 'Thanks for commenting'
      redirect_to talk_path(@comment.talk)
    else
      flash[:alert] = "You cannot submit a blank comment"
      redirect_to edit_talk_path(@comment.talk, @comment)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @talk = @comment.talk
    if @comment.destroy
      flash[:notice] = "You have deleted your comment"
    else
      flash[:alert] = "Your comment cannot be deleted"
    end
    redirect_to talk_path(@talk)
  end
end

app/controllers/emcee_controller.rb
class EmceeController < ApplicationController
  before_action :authenticate_user!

  def index
    flash[:notice] = "Those are all of the lighting talks. Thank you for listening"
    @talks = Talk.where(date: Date.today)
  end

  def new
    @emcee = current_user
  end

  def create
    @user = current_user
    parsed = params[:user][:emcee].split('-').map { |i| i.to_i }
    @date = Date.new(parsed[0], parsed[1], parsed[2])
    @user.emcee = @date
    if @user.save
      flash[:notice] = @date.strftime("You are the emcee for lighting talks on %B %-d")
      redirect_to speaker_path(@user)
    end
  end

  def show
    @talk = Talk.find(params[:id])
    redirect_to talk_path(@talk)
  end

  def edit
    @emcee = current_user
  end

  def destroy
    @user = current_user
    flash[:notice] =  @user.emcee.strftime("You are no longer the emcee for lighting talks on %B %-d")
    @user.emcee = ""
    @user.save
    redirect_to talks_path
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  def new
    @talk = Talk.find(params[:talk_id])
    redirect_to talk_path(@talk)
    start_recording(@talk)
  end

  def create
    @talk = Talk.find(params[:talk_id])
    speech_processor = SpeechProcessor.new
    @talk.transcript = speech_processor.decode("#{@talk.id}.wav")
    @talk.save
    redirect_to talk_path(@talk)
  end

  def start_recording(talk)
    dev = CoreAudio.default_input_device
    buf = dev.input_buffer(1024)

    wav = CoreAudio::AudioFile.new("#{talk.id}.wav", :write, format: :wav,
                                   rate: dev.nominal_rate,
                                   channels: dev.input_stream.channels)
    samples = 0
    th = Thread.start do
      loop do
        w = buf.read(4096)
        samples += w.size / dev.input_stream.channels
        wav.write(w)
      end
    end

    buf.start
    sleep 10
    buf.stop
    th.kill.join

    wav.close
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def show
    @user = current_user
    @talks = @user.talks
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @talks = Talk.all
  end

  def new
    @talk = Talk.new
  end

  def create
    talk_params[:video_url].gsub!("watch?v=","embed/")
    @talk = Talk.new(talk_params)
    @talk.user_id = current_user.id
    if @talk.save
      flash[:notice] = 'You have scheduled a lighting talk!'
      redirect_to root_path
    else
      @talk.errors.full_messages.each { |error| flash[error] = error }
      redirect_to new_talk_path
    end
  end

  def show
    @talks = Talk.where(date: Date.today)
    @talk = Talk.find(params[:id])
    @comments = @talk.comments
    @comment = Comment.new
    @filler_counts = @talk.count_fillers
  end

  def edit
    @talk = Talk.find(params[:id])
  end

  def update
    @talk = Talk.find(params[:id])
    if params[:talk][:transcript]
      @talk.transcript = params[:talk][:transcript].gsub(/\s{2,}/,' ').lstrip.rstrip
      @talk.find_wasted_words
    else
      @talk.update(talk_params)
    end

    if @talk.save
      flash[:notice] = 'You have updated a lighting talk!'
      redirect_to talk_path(@talk)
    else
      @talk.errors.full_messages.each { |error| flash[error] = error }
      redirect_to edit_talk_path
    end
  end

  def destroy
    flash[:notice] = 'You have deleted a lighting talk!'
    Talk.destroy(params[:id])
    redirect_to talks_path
  end


  protected

  def talk_params
    params.require(:talk).permit(:topic, :date, :description, :video_url)
  end
end

app/views/comments/_form.html.erb
<%= form_for [@talk, @comment] do |f| %>
  <%= f.label :content, "Comment:" %>
  <%= f.text_area :content %>

  <%= f.submit (f.object.new_record?) ? "Add Comment" : "Edit Comment", class: "button medium radius" %>
<%-end-%>

app/views/comments/edit.html.erb
<h3>Update review</h3>
<%= render 'form' %>

app/views/emcee/_form.html.erb
<%= form_for :user, url: { action: "create", id: @emcee } do |f| %>
  <%= f.label :emcee, "Lighting Talk Date" %>
  <%= f.date_field(:emcee)%>
  <%= f.submit "Emcee Lighting Talks" %>
<%-end-%>

app/views/emcee/edit.html.erb
<%= render 'form' %>

app/views/emcee/index.html.erb
<%= link_to "Start Lighting Talks", emcee_path(@talks.first), class: "button radius" %>

app/views/emcee/new.html.erb
<%= render 'form' %>

app/views/emcee/show.html.erb
<p>Those are all of the lighting talk. Thank you for listenin</p>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>LightingTalksApp</title>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= csrf_meta_tags %>
</head>
<body>

<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
    <h1><a href="/">Lighting Talks!</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li><%= link_to "Profile", speaker_path(current_user) %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    <%- else -%>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
    <%- end -%>
    </ul>
  </section>
</nav>

<div class="container">
  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
    <%= value %>
  </div>
<%- end -%>
  <%= yield %>
</div>

<%= javascript_include_tag 'application' %>
<%= yield :extra_footer %>
</body>
</html>

app/views/speakers/show.html.erb
<%= link_to 'Emcee for lighting talks', new_emcee_path %>
<%= @user.emcee.strftime("You are the emcee for lighting talks on %B %-d") unless @user.emcee.nil? %>
<%= link_to "Edit", edit_emcee_path %>
<%= link_to "Delete", emcee_path, method: :delete %>
<% @talks.each do |talk| %>
  <%= link_to talk.topic, talk_path(talk) %>
<%-end-%>

app/views/talks/_transcript.html.erb
<%= form_for @talk do |f| %>
  <%= f.label :transcript %>
  <%= f.text_area :transcript %>
  <%= f.submit 'Analyze Transcript' %>
<%-end-%>

app/views/talks/edit.html.erb
<%= form_for @talk do |f| %>
  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <%= f.label :date %>
  <%= f.date_field(:date)%>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :video_url, 'Video URL' %>
  <%= f.text_field :video_url %>

  <%= f.submit 'Update', class: "button radius" %>
<%-end-%>

app/views/talks/index.html.erb
<h1> Below is a list of lighting talks! </h1>
<%= link_to 'Do a lighting talk!', new_talk_path, class: "button radius" unless current_user.nil? %>
<% unless current_user.nil? %>
  <%= link_to 'Emcee Lighting Talks', emcee_index_path, class: "button radius" if current_user.emcee == Date.today  %>
<%-end-%>
<% unless @talks.empty? %>
  <% @talks.each do |talk| %>
<div class="row">
  <div class="small-12 columns">
    <h3><%= link_to talk.topic, talk_path(talk) %></h3>
  </div>
</div>
<div class="row">
  <div class="small-6 columns">
    <p><%= talk.date.strftime("Scheduled for %B %-d, %Y ") %></p>
  </div>
  <div class="small-6 columns">
    <p> Presented by <%= talk.user.email %></p>
  </div>
</div>

  <%-end-%>
<%-end-%>

app/views/talks/new.html.erb
<%= form_for @talk do |f| %>
  <%= f.label :topic %>
  <%= f.text_field :topic %>

  <%= f.label :date %>
  <%= f.date_field(:date)%>

  <%= f.label :video_url, 'Video URL' %>
  <%= f.text_field :video_url %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit 'Add Talk', class: "button radius" %>
<%-end-%>

app/views/talks/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2><%= @talk.topic %></h2>
  </div>
</div>
<div class="row">
  <div class="small-6 columns">
    <p> <%= @talk.date.strftime("Scheduled for %B %-d, %Y") %> </p>
  </div>
  <div class="small-2 columns">
    <%= link_to "Edit Talk", edit_talk_path, class: "button radius tiny" if @talk.user == current_user %>
  </div>
  <div class="small-2 columns">
    <%= link_to "Delete Talk", talk_path, method: :delete, class: "button alert radius tiny" if @talk.user == current_user%>
  </div>
  <div class="small-2 columns">
    <% unless current_user.nil? %>
      <% if current_user.emcee == Date.today %>
      <% current_talk_index = @talks.index(@talk) %>
    <% next_talk = @talks[current_talk_index + 1] unless current_talk_index.nil? %>
    <%= link_to "Next Talk", talk_path(next_talk), class: "button success" unless next_talk.nil? %>
    <%= link_to "Next Talk", emcee_index_path, class: "button success radius tiny"  if next_talk.nil? %>
  <%-end-%>
  <%-end-%>
  </div>
</div>

<% unless @talk.video_url.nil? || @talk.video_url.empty?  %>
  <iframe id="ytplayer" type="text/html" width="640" height="390" src=<%= @talk.video_url %>></iframe>
<%-end-%>
<%= link_to "Record Talk", new_talk_recording_path(@talk) %>
<%= link_to "Analyze Recorded Talk", talk_recordings_path(@talk), method: :post %>
<%= render 'transcript' %>

<% unless @filler_counts.empty? %>
<h4>These are the filler words you said </h4>
<%-end-%>

<% if @filler_counts.empty? && !@talk.transcript.nil? %>
<h4>You didn't say any filler words</h4>
<%-end-%>

<p>
<% @filler_counts.each_pair do |filler, count| %>
  <%= "#{filler.capitalize} #{count}" %>
<%-end-%>
</p>

<%= render 'comments/form' %>
<% unless @comments.empty? %>
  <% @comments.each do |comment| %>
  <div class="panel callout radius">
  <div class="row">
    <div class="small-6 small-offset-6">
      <%= comment.created_at.strftime("#{comment.user.email} commented on %B %-d, %Y at %k:%M") %>
    </div>
  </div>
  <div class="row">
    <div class="small-8 columns">
      <%= comment.content %>
    </div>
    <div class="small-2 columns">
      <%= link_to "Edit", edit_talk_comment_path(@talk,comment), id: "edit-comment-#{comment.id}", class: "button radius tiny" if comment.user == current_user %>
    </div>
    <div class="small-2 columns">
      <%= link_to "Delete",talk_comment_path(@talk,comment), method: :delete, id: "delete-comment-#{comment.id}", class: "button radius tiny alert" if comment.user == current_user %>
    </div>
  </div>
</div>
<%-end-%>
</div>
<%-end-%>